### ISSUE TITLE
sdsc_atlas_module is not installed on run

### ISSUE THREAD

**Issue by ybarlev** [sdsc/atlas-roll#1]
sdsd_atlas_module is not installed on "rocks run roll atlas | bash"
however it IS part of the distro. If sdsc_atlas_modules RPM is installed manually atlas passes all the tests.

**Comment by jjhayes** [comment]
Looks like a bug in the node file.  Thanks for reporting; we'll get it fixed.

Jim

**Comment by ybarlev** [comment]
# Thanks. Also the module does not appear when "module avail" is used. Probably because a dot is used in the path ".gnu/atlas". Is is done on purpose?

Sorry. My bad. Didn't know about this feature of Modules. The module is only available when "module gnu" is loaded.

**Comment by jjhayes** [comment]
Correct.  We place modules for compiler-dependent applications (libraries, mostly) in "hidden" directories so that they are available only if the compiler module is loaded first.  This reduces the chance of accidental mixing of code compiled with one compiler with incompatible libraries compiled with another.

If you're only installing the gnu compiler, the easiest way to work with this is to include "module load gnu" in an /etc/profile.d script that will be run automatically on user login.

**Comment by jjhayes** [comment]
Installation of atlas modulefiles resolved by commit 24efb1244924fa3fb12804366403fffdfbb34249.
